spring:
  profiles:
    default: homol
  application:
    name: dsList

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        "[generate_statistics]": true

  # Swagger
# springdoc:
#   swagger-ui:
#     filter: true
#     use-root-path: true
#   show-login-endpoint: true
#   api-docs:
#     path: /v3/api-docs

# cors:
#   allowedOriginPatterns: ${ALLOWD_ORIGIN_PATTERNS}

      
  
