logging:
  level:
    "[org.hibernate.stat]": debug

spring:
  devtools:
    add-properties: false

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    properties:
      "[hibernate.format_sql]": true
      "[hibernate.generate_statistics]": true
      "[persistence.schema-generation.scripts.create-target]": create.sql
